### ISSUE TITLE
Nom del dipòsit de GitHub

### ISSUE THREAD

**Issue by jordimas** [Softcatala/SoftcatalaTelegramBot#5]
Trobo que SoftcatalàBot és massa genèric. Trobo que SoftcatalàBot és massa genèric.  Com a mínim, ko l'hagues dit SoftcatalaTelegramBot perquè quedi clar la plataforma.  No sé si la idea és que només gestioni canals de xats o també les traduccions.

Si s'acabés escollint un nom nou, a través dels Settings es pot canviar el nom.

Salut

Jordi

**Comment by KonfrareAlbert** [comment]
Tota la raó @jordimas .
Ja he canviat el nom del dipòsit.

Gràcies
